on:
  push:
    branches:
      - main
name: create-release

permissions:
  contents: write
  pull-requests: write
  id-token: none

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4
        id: release
      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 22.x
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Make envfile
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo APP_INSIGHT_INSTRUMENT_KEY=${{ secrets.APP_INSIGHT_INSTRUMENT_KEY }} >> .env
      - run: yarn install
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn run compile
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn run vsce package --yarn --allow-package-env-file -o artifact.vsix
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn run vsce publish -p $VSCE_TOKEN --yarn -i artifact.vsix
        if: ${{ steps.release.outputs.release_created }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      - run: npm install -g ovsx
        if: ${{ steps.release.outputs.release_created }}
      - run: ovsx publish -p $OVSX_TOKEN --yarn -i artifact.vsix
        if: ${{ steps.release.outputs.release_created }}
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}